import {PageDataFilter} from "@/appTypes/base"
import {ProductModel} from "@/appTypes/products/product"
import {ToasterProps} from "react-hot-toast"

export const OFFICE_ADDRESS = "GstPlace Limited , 4th Floor, Silverbird Entertainment and Gallery Centre,  By  Yar'dua Centre, Central Business District, Abuja. Nigeria"
export const SUPPORT_LINE = "09056240621"
export const SUPPORT_LINE_2 = "07084476483"
export const SUPPORT_EMAIL = "hello@gstplace.com"
export const OPENING_HOURS = ["Monday to Saturday: 9am - 9pm", "Sundays: 1pm - 7:30pm"]
export const DEFAULT_LOGO = "https://res.cloudinary.com/dh4czj7l1/image/upload/v1747819519/logo.jpg";

export const TOASTER_PROPS: ToasterProps = {
    position: "top-right",
    toastOptions: {
        style: {
            fontSize: "0.875rem",
        },
        duration: 4000,
        success: {
            style: {
                backgroundColor: "#DCFCE7",
                color: "#14532D",
            },
        },
    },
};

export const DEFAULT_PAGE_FILTERS: PageDataFilter = {
    limit: 5,
    page: 1,
    order: "desc",
    search: "",
};

export const DUMMY_PRODUCTS: ProductModel[] = [
    {
        "id": 1,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 56789,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "currency": "NGN",
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
    {
        "id": 2,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 345,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
    {
        "id": 3,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 987,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
    {
        "id": 4,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 987,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
    {
        "id": 5,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 6898,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
    {
        "id": 6,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 8765,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
    {
        "id": 7,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 234567,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
    {
        "id": 8,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 9876,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
    {
        "id": 10,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 9776,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
    {
        "id": 11,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 9876,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
    {
        "id": 12,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 8765,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
    {
        "id": 13,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 8765,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
    {
        "id": 14,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 46567,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
    {
        "id": 15,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 755678,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
    {
        "id": 16,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 86568,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
    {
        "id": 17,
        "categoryId": 7,
        "divisionId": 2,
        "sku": "nMRkBP",
        "name": "Totam consequatur animi qui aliquid quod laborum.",
        "slug": "temporibus-facilis-vitae-voluptatibus-voluptatem-quibusdam-tenetur-commodi-ullam",
        "description": "Voluptas ducimus fugiat explicabo fugit voluptatem fugiat qui quia sint voluptatem eligendi eos corporis nam totam qui accusamus molestias.",
        "price": 8173,
        "prevPrice": 1390,
        "currency": "USD",
        "countryCode": "NGA",
        "state": "Abuja",
        "stock": 36,
        "productValue": 3,
        "dimensionL": 40,
        "dimensionW": 43,
        "dimensionH": 40,
        "weight": 40,
        "published": 1,
        "hasWarrant": 0,
        "requiresInsurance": 0,
        "deletedAt": null,
        "createdAt": "2024-11-05T10:47:13.000000Z",
        "updatedAt": "2025-05-09T16:42:39.000000Z",
        "images": [],
        "category": {
            "id": 7,
            "parentId": 1,
            "name": "Others",
            "slug": "Others3592480163",
            "createdAt": "2025-05-20T13:21:58.000000Z",
            "updatedAt": "2025-05-20T13:21:58.000000Z"
        },
        "division": {
            "id": 2,
            "name": "Luxury",
            "slug": "luxury",
            "description": null,
            "image": "logo.png",
            "deletedAt": null,
            "createdAt": null,
            "updatedAt": null
        },
        "variants": [
            {
                "id": 1,
                "productId": 1,
                "divisionId": 1,
                "name": "Tempore autem rerum quos ex.",
                "price": 98765,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 28,
                "sku": "9605234589171",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-10-22T19:58:24.000000Z",
                "updatedAt": "2025-05-01T02:51:39.000000Z"
            },
            {
                "id": 2,
                "productId": 1,
                "divisionId": 1,
                "name": "Non ea ea qui natus.",
                "price": 1734.0,
                "currency":"NGN",
                "countryCode": "NGA",
                "state": "Abuja",
                "stock": 92,
                "sku": "4878271065129",
                "dimensionL": 0,
                "dimensionW": 0,
                "dimensionH": 0,
                "weight": 0,
                "published": 1,
                "hasWarrant": 0,
                "requiresInsurance": 0,
                "createdAt": "2024-09-21T19:34:04.000000Z",
                "updatedAt": "2024-10-03T06:58:48.000000Z"
            }
        ],
    },
]

export enum PRODUCT_FILTER_TYPE {
    FEATURED = "featured",
    LUXURY = "luxury",
    FAST_SELLING = "fast-selling",
    LIMITED_STOCK = "limited-stock",
    CHILDREN = "children",
    NEW_ARRIVAL = "new-arrival",
}


export const DEFAULT_CHECKOUT_PAYMENT_METHOD = "wallet"

interface FilterParams {
    search: string;
    category: string[];
    division: string[];
    filter_name?: string;
    filter_dir?: string;
    filter_val?: string;
    range_start?: number;
    range_end?: number;
    page: number;
    latest?: boolean;
    sort_dir?: string;

}

export const DEFAULT_PAGINATED_PRODUCTS_FILTERS: FilterParams = {
    search: "",
    category: [],
    division: [],
    filter_name: "",
    filter_dir: "",
    filter_val: "",
    range_start: 0,
    range_end: 500000,
    page: 1,
};